feat(backup): New backup service and checks
prowler-cloud/prowler pull request #2172
Opened 2023-04-05 04:38 UTC by gabrielsoltz

### Context

I'm adding a new service `backup` with four new checks:

- `backup_plans_exist`: Ensure that there is at least one AWS Backup plan (medium)
- `backup_reportplans_exist`: Ensure that there is at least one AWS Backup report plan (low)
- `backup_vaults_encrypted`: Ensure that AWS Backup vaults are encrypted with AWS KMS (medium)
- `backup_vaults_exist`: Esure AWS Backup vaults exist (medium)

### Description

This PR introduces a new service for `backup` with four checks. 

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-05 11:27 UTC, n4ch04 requested changes

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_service.py
> +################## Organizations
```suggestion
################## Backup
```

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_reportplans_exist/backup_reportplans_exist.py
> +        for backup_report_plan in backup_client.backup_report_plans:
Here we should only check for the existence of backup plans, not iterating over all.
I would suggest to do something like this:

```
def execute(self):
    findings = []
    report = Check_Report_AWS(self.metadata())
    report.status = "FAIL"
    report.status_extended =  "No Backup Report Plan Exist"
    report.resource_arn = ""
    report.resource_id = "No Backups"
    report.region = backup_client.general_region # this will come from the service, please check 
    the service file
    if backup_client.backup_report_plans: # we check if the list is not empty
        report.status = "PASS"
        report.status_extended =  f"At least one backup report plan exists: 
        { backup_client.backup_report_plans[0].name}"
        report.resource_arn = backup_client.backup_report_plans[0].arn
        report.resource_id =  backup_client.backup_report_plans[0].name
        report.region =  backup_client.backup_report_plans[0].region

    findings.append(report)
    return findings
```
This will follow the v3 checks structure (if it looks for at least one backup report plan it will only return one finding)

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +        for backup_plan in backup_client.backup_plans:
Here we should only check for the existence of backups plans, not iterating over all.
I would suggest to do something like this:

```
def execute(self):
    findings = []
    report = Check_Report_AWS(self.metadata())
    report.status = "FAIL"
    report.status_extended =  "No Backup  Plan Exist"
    report.resource_arn = ""
    report.resource_id = "No Backups"
    report.region = backup_client.general_region # this will come from the service, please check 
    the service file
    if backup_client.backup_plans: # we check if the list is not empty
        report.status = "PASS"
        report.status_extended =  f"At least one backup plan exists: 
        { backup_client.backup_plans[0].name}"
        report.resource_arn = backup_client.backup_plans[0].arn
        report.resource_id =  backup_client.backup_plans[0].name
        report.region =  backup_client.backup_plans[0].region

    findings.append(report)
    return findings
```

This will follow the v3 checks structure (if it looks for at least one backup plan it will only return one finding)

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_service.py
> +        self.regional_clients = generate_regional_clients(self.service, audit_info)
Add here a general region coming from the `audit_info.profile_region` to assign it in case of no findings in the checks.
```
self.general_region = audit_info.profile_region
```

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_vaults_encrypted/backup_vaults_encrypted.py
> +            if backup_vault.encryption:
With this kind of login we usually follow the following structure
```
# By default we assume that the result is fail
report = Check_Report_AWS(self.metadata())
report.status = "FAIL"
report.status_extended = f"Backup Vault {backup_vault.name} is not encrypted"
report.resource_arn = backup_vault.arn
report.resource_id = backup_vault.name
report.region = backup_vault.region
# if it is encrypted we only change the status and the status extended
if backup_vault.encryption:
    report.status = "PASS"
    report.status_extended = f"Backup Vault {backup_vault.name} is encrypted"
# then we store the finding
findings.append(report)
```
Of course your logic is valid, but this implies less code
What do you think?

2023-04-05 11:27 UTC, n4ch04 commented on prowler/providers/aws/services/backup/backup_vaults_exist/backup_vaults_exist.py
> +        for backup_vault in backup_client.backup_vaults:
Please, change here the logic like in the checks `backup_plans_exist` and `backup_reportplans_exist`

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_plans_exist/backup_plans_exist_test.py
> +class Test_backup_plans_exist:
Please, once the check follows the v3 structure adapt the tests

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_reportplans_exist/backup_reportplans_exist_test.py
> +class Test_backup_reportplans_exist:
Same here, adapt the tests once the check is modifiied

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_service_test.py
> +# Mocking Access Analyzer Calls
```suggestion
# Mocking Backup Calls
```

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_service_test.py
> +    As you can see the operation_name has the list_analyzers snake_case form but
Delete this two lines please or make it general, since it references another service

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_service_test.py
> +from prowler.providers.aws.lib.audit_info.audit_info import current_audit_info
Please, mock the `audit_info` object instead of import it in order to avoid race conditions

2023-04-05 11:27 UTC, n4ch04 commented on tests/providers/aws/services/backup/backup_vaults_exist/backup_vaults_exist_test.py
> +class Test_backup_vaults_exist:
Please adapt the tests once the check is modified

2023-04-05 11:28 UTC, n4ch04 commented
Really nice job @gabrielsoltz !!! 
Just a few comments mainly to adapt checks logic to v3 checks structure

2023-04-05 18:36 UTC, gabrielsoltz commented
Thank you @n4ch04, for reviewing, all changes implemented.

2023-04-11 05:42 UTC, n4ch04 approved these changes

2023-04-11 05:43 UTC, merged

2023-04-11 05:43 UTC, n4ch04 commented
Amazing work @gabrielsoltz  !!