refactor(tags): convert tags to a dictionary
prowler-cloud/prowler pull request #4598
Opened 2024-07-31 18:24 UTC by sergargar

### Context

Fix #4597

### Description

Convert all Prowler tags to a dictionary for a better formatting and handling of the attribute across all the providers.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-01 10:24 UTC, jfagoagas requested changes
Not sure about the content of this PR. We need to talk about it.

2024-08-01 10:24 UTC, jfagoagas commented on docs/tutorials/reporting.md
> +            "labels": {},
We cannot do this, this is not compatible with the OCSF format. https://schema.ocsf.io/1.2.0/objects/resource_details?extensions=

2024-08-01 10:24 UTC, jfagoagas commented on prowler/lib/mutelist/mutelist.py
> +        print(finding_tags)
```suggestion
```

2024-08-01 10:24 UTC, jfagoagas commented on prowler/lib/outputs/ocsf/ocsf.py
> +                            labels=finding.resource_tags,
This needs to be reverted, `labels` must be a String Array.

2024-08-01 10:24 UTC, jfagoagas commented on prowler/lib/outputs/utils.py
> +            unrolled_items = f"{key}={value}"
Why this change in formatting?

2024-08-01 10:24 UTC, jfagoagas commented on tests/lib/outputs/csv/csv_test.py
> +        expected_csv = f"AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHECK_T
We cannot change the CSV tags format.

2024-08-01 12:33 UTC, MrCloudSec commented on prowler/lib/mutelist/mutelist.py
> +                    muted_in_tags = self.is_tag_matched(muted_tags, finding_tags)
```suggestion
                    muted_in_tags = self.is_item_matched(muted_tags, finding_tags)
```

2024-08-01 12:33 UTC, MrCloudSec commented on prowler/lib/mutelist/mutelist.py
> +                is_tag_excepted = self.is_tag_matched(excepted_tags, finding_tags)
```suggestion
                is_tag_excepted = self.is_item_matched(excepted_tags, finding_tags)
```

2024-08-01 12:33 UTC, MrCloudSec commented on prowler/lib/mutelist/mutelist.py
> +            return False
```suggestion
```

2024-08-01 12:38 UTC, sergargar commented on tests/lib/outputs/csv/csv_test.py
> +        assert output_data["COMPLIANCE"] == "compliance_key=compliance_value"
```suggestion
        assert output_data["COMPLIANCE"] == "compliance_key: compliance_value"
```

2024-08-01 12:38 UTC, sergargar commented on tests/lib/outputs/csv/csv_test.py
> +        expected_csv = f"AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHECK_T
```suggestion
        expected_csv = f"AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHECK_TYPE;STATUS;STATUS_EXTENDED;MUTED;SERVICE_NAME;SUBSERVICE_NAME;SEVERITY;RESOURCE_TYPE;RESOURCE_UID;RESOURCE_NAME;RESOURCE_DETAILS;RESOURCE_TAGS;PARTITION;REGION;DESCRIPTION;RISK;RELATED_URL;REMEDIATION_RECOMMENDATION_TEXT;REMEDIATION_RECOMMENDATION_URL;REMEDIATION_CODE_NATIVEIAC;REMEDIATION_CODE_TERRAFORM;REMEDIATION_CODE_CLI;REMEDIATION_CODE_OTHER;COMPLIANCE;CATEGORIES;DEPENDS_ON;RELATED_TO;NOTES;PROWLER_VERSION\r\nprofile: default;{datetime.now()};123456789012;123456789012;;test-organization-id;test-organization;test-tag:test-value;test-unique-finding;aws;test-check-id;test-check-id;test-type;PASS;;False;test-service;;high;test-resource;;;;;aws;eu-west-1;check description;test-risk;test-url;;;;;;;test-compliance: test-compliance;test-category;test-dependency;test-related-to;test-notes;{prowler_version}\r\n"
```

2024-08-01 12:39 UTC, sergargar commented on tests/lib/outputs/csv/csv_test.py
> +            expected_csv = f"AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHE
```suggestion
            expected_csv = f"AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHECK_TYPE;STATUS;STATUS_EXTENDED;MUTED;SERVICE_NAME;SUBSERVICE_NAME;SEVERITY;RESOURCE_TYPE;RESOURCE_UID;RESOURCE_NAME;RESOURCE_DETAILS;RESOURCE_TAGS;PARTITION;REGION;DESCRIPTION;RISK;RELATED_URL;REMEDIATION_RECOMMENDATION_TEXT;REMEDIATION_RECOMMENDATION_URL;REMEDIATION_CODE_NATIVEIAC;REMEDIATION_CODE_TERRAFORM;REMEDIATION_CODE_CLI;REMEDIATION_CODE_OTHER;COMPLIANCE;CATEGORIES;DEPENDS_ON;RELATED_TO;NOTES;PROWLER_VERSION\nprofile: default;{datetime.now()};123456789012;123456789012;;test-organization-id;test-organization;test-tag:test-value;test-unique-finding;aws;test-check-id;test-check-id;test-type;PASS;;False;test-service;;high;test-resource;;;;;aws;eu-west-1;check description;test-risk;test-url;;;;;;;test-compliance: test-compliance;test-category;test-dependency;test-related-to;test-notes;{prowler_version}\n"
```

2024-08-01 15:03 UTC, jfagoagas requested changes

2024-08-01 15:03 UTC, jfagoagas commented on tests/lib/outputs/asff/asff_test.py
> +                    Tags=(finding.resource_tags if finding.resource_tags else None),
```suggestion
                    Tags=finding.resource_tags,
```

2024-08-01 15:03 UTC, jfagoagas commented on tests/lib/outputs/asff/asff_test.py
> +                    Tags=(finding.resource_tags if finding.resource_tags else None),
```suggestion
                    Tags=finding.resource_tags,
```

2024-08-01 15:03 UTC, jfagoagas commented on tests/lib/outputs/asff/asff_test.py
> +                    Tags=(finding.resource_tags if finding.resource_tags else None),
```suggestion
                    Tags=finding.resource_tags,
```

2024-08-01 15:03 UTC, jfagoagas commented on tests/lib/outputs/asff/asff_test.py
> +                    Tags=(finding.resource_tags if finding.resource_tags else None),
```suggestion
                    Tags=finding.resource_tags,
```

2024-08-01 15:03 UTC, sergargar commented on prowler/lib/outputs/asff/asff.py
> +                                ),
```suggestion
                                Tags=finding.resource_tags,
```

2024-08-01 16:00 UTC, jfagoagas requested changes
Could you please add the finding type to the `is_finding_muted` method in each provider's Mutelist class?

2024-08-02 09:40 UTC, jfagoagas approved these changes, later dismissed
Now I can approve it, my 🧠 can rest since the tests covers all the changes in tags and everything works 💯 🚀

2024-08-02 09:48 UTC, pedrooot commented
🔝 @jfagoagas 
![programming](https://github.com/user-attachments/assets/1efe6d43-92d4-4c15-95ea-02957fa376a0)

2024-08-05 06:17 UTC, jfagoagas approved these changes

2024-08-05 06:17 UTC, merged