feat(gcp): add a test_connection method
prowler-cloud/prowler pull request #4616
Opened 2024-08-02 17:33 UTC by sergargar

### Context

We need to be able to test the connection to each provider using one of the available authentication methods, starting from the environment variables.

### Description
Add a `test_connection` method for the GCP provider.
Create a `test_connection` abstract method in the Provider class but not enforced for now not to break anything.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-09 13:50 UTC, jfagoagas requested changes, later dismissed

2024-08-09 13:50 UTC, jfagoagas commented on prowler/providers/gcp/gcp_provider.py
> +        credentials_file: str, service_account: str, raise_on_exception: bool = True
Is it mandatory to set the `credentials_file` or `service_account`? If not please set some default values.

2024-08-09 13:50 UTC, jfagoagas commented on prowler/providers/gcp/gcp_provider.py
> +        Test the connection with the provided credentials file or service account to impersonate
Improve the docstring with the possible exceptions raised, what the method do and more about the args and returns please.

2024-08-09 13:50 UTC, jfagoagas commented on prowler/providers/gcp/gcp_provider.py
> +                raise Exception(
Remember to add `if raise_on_exception`.

2024-08-09 13:50 UTC, jfagoagas commented on tests/providers/gcp/gcp_provider_test.py
Please add tests for the `test_connection` method.

2024-08-19 10:38 UTC, pedrooot requested changes

2024-08-19 10:38 UTC, pedrooot commented on prowler/providers/gcp/gcp_provider.py
> +        """
Could you add docstrings following the guide from https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings please? Thanks!

2024-08-19 16:08 UTC, pedrooot approved these changes
🔝 Thanks for this amazing feature!!

2024-08-19 16:11 UTC, merged