feat(kubernetes): add a test_connection method
prowler-cloud/prowler pull request #4684
Opened 2024-08-07 13:18 UTC by sergargar

### Context

We need to be able to test the connection to each provider using one of the available authentication methods, starting from the environment variables.

### Description

Add a test_connection method for the Kubernetes provider.
Create a test_connection abstract method in the Provider class but not enforced for now not to break anything.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-09 11:37 UTC, jfagoagas requested changes

2024-08-09 11:37 UTC, jfagoagas commented on prowler/providers/kubernetes/kubernetes_provider.py
> +    def test_connection(kubeconfig_file, input_context) -> KubernetesSession:
```suggestion
    def test_connection(kubeconfig_file: str, input_context: str, raise_on_exception: bool = True) -> Connection:
```

Merge from `master` to get the `Connection` object:
```python

@dataclass
class Connection:
    is_connected: bool = False
    error: Exception = None
```

2024-08-09 11:37 UTC, jfagoagas commented on prowler/providers/kubernetes/kubernetes_provider.py
> +            raise error
```suggestion
            if raise_on_exception:
               raise error
            return Connection(error=error)
```

2024-08-09 11:37 UTC, jfagoagas commented on prowler/providers/kubernetes/kubernetes_provider.py
> +            return session
```suggestion
            return Connection(is_connected=True)
```

2024-08-09 11:37 UTC, jfagoagas commented on prowler/providers/kubernetes/kubernetes_provider.py
> +        )
This should be a call to setup_session.

2024-08-09 12:47 UTC, jfagoagas requested changes, later dismissed

2024-08-09 12:47 UTC, jfagoagas commented on prowler/providers/kubernetes/kubernetes_provider.py
> +        kubeconfig_file: str, input_context: str, raise_on_exception: bool = True
We need to add default values here because as far as I know this function in K8s can be called without them.

2024-08-19 10:40 UTC, pedrooot requested changes

2024-08-19 10:40 UTC, pedrooot commented on prowler/providers/kubernetes/kubernetes_provider.py
> +        """
Could you add docstrings following the guide from https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings please? Thanks!

2024-08-19 16:08 UTC, pedrooot approved these changes
🚀  Thanks for this amazing feature!!

2024-08-19 16:12 UTC, merged