feat(CodeBuild): Ensure no sensitive credentials are in bitbucket ur ls
prowler-cloud/prowler pull request #4731
Opened 2024-08-13 09:36 UTC by MarioRgzLpz

### Context

Please include relevant motivation and context for this PR.

If fixes an issue please add it with `Fix #XXXX`

### Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-13 14:58 UTC, sergargar requested changes
As the title of the check in Security Hub is "CodeBuild Bitbucket source repository URLs should not contain sensitive credentials", I would make this check to analyze every repository URL and not only BitBucket URL. And also using the detect secrets library.

2024-08-14 13:29 UTC, sergargar commented
Please name the check `codebuild_project_source_no_sensitive_credentials` and include the logic of checking if the source is not using OAuth with a GitHub source or if it is using PATs with GitHub enterprise (basically checking if there are clear text credentials in any type of source). 

Also, please create a BaseModel called Source to fill it with the information needed.

2024-08-20 12:22 UTC, sergargar commented on prowler/providers/aws/services/codebuild/codebuild_project_source_repo_url_no_sensitive_credentials/codebuild_project_source_repo_url_no_sensitive_credentials.py
> +            report.status_extended = f"CodeBuild project {project.name} does not contain sensitive credentials in source repository URLs."
```suggestion
            report.status_extended = f"CodeBuild project {project.name} does not contain sensitive credentials in any source repository URLs."
```

2024-08-20 12:23 UTC, sergargar commented on prowler/providers/aws/services/codebuild/codebuild_project_source_repo_url_no_sensitive_credentials/codebuild_project_source_repo_url_no_sensitive_credentials.py
> +                    secrets_found.append(f"Token in URL {project.source.location}")
```suggestion
                    secrets_found.append(f"Token in {project.source.type} URL {project.source.location}")
```

2024-08-20 12:23 UTC, sergargar commented on prowler/providers/aws/services/codebuild/codebuild_project_source_repo_url_no_sensitive_credentials/codebuild_project_source_repo_url_no_sensitive_credentials.py
> +                        f"Basic Auth Credentials in URL {project.source.location}"
```suggestion
                        f"Basic Auth Credentials in {project.source.type} URL {project.source.location}"
```

2024-08-20 12:23 UTC, sergargar commented on prowler/providers/aws/services/codebuild/codebuild_project_source_repo_url_no_sensitive_credentials/codebuild_project_source_repo_url_no_sensitive_credentials.py
> +                        secrets_found.append(f"Token in URL {url.location}")
```suggestion
                        secrets_found.append(f"Token in {url.type} URL {url.location}")
```

2024-08-20 12:24 UTC, sergargar commented on prowler/providers/aws/services/codebuild/codebuild_project_source_repo_url_no_sensitive_credentials/codebuild_project_source_repo_url_no_sensitive_credentials.py
> +                            f"Basic Auth Credentials in URL {url.location}"
```suggestion
                            f"Basic Auth Credentials in {url.type} URL {url.location}"
```

2024-08-20 12:24 UTC, sergargar requested changes
Please, review my changes for a more detailed status extended.

2024-08-20 12:57 UTC, MarioRgzLpz commented
@sergargar All the changes requested done in commit  64bade9.

2024-08-20 13:40 UTC, sergargar approved these changes
❤️

2024-08-20 13:44 UTC, merged