feat(aws): Add new RDS check for deletion protection enabled on clusters
prowler-cloud/prowler pull request #4738
Opened 2024-08-14 09:03 UTC by danibarranqueroo

### Context

This new check will verify that deletion protection is enabled for Amazon RDS DB clusters. Enabling deletion protection provides a critical safeguard against accidental or unauthorized deletions, ensuring that the clusters cannot be removed without explicitly disabling this setting first.

When you try to create a new RDS database, there is an option in the additional configuration that allows you to enable deletion protection with the following description: "Protects the database from being deleted accidentally. While this option is enabled, you can’t delete the database." This check verifies that every DB cluster has this option enabled.

### Description

I added `rds_cluster_deletion_protection` with its respective unit test.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-14 13:32 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_cluster_deletion_protection/rds_cluster_deletion_protection.metadata.json
> +      "CLI": "aws rds modify-db-instance --db-instance-identifier <db_instance_id> --deletion-protection --apply-immediately",
Please, change the CLI command for the cluster one.

2024-08-14 13:33 UTC, sergargar requested changes
I think we should remove the cluster logic from the check `rds_instance_deletion_protection`, what do you think?

2024-08-14 14:02 UTC, danibarranqueroo commented
Yes, good point. We can do it the same way we did in #4730

2024-08-20 12:31 UTC, sergargar approved these changes
👏🏼

2024-08-20 13:07 UTC, merged