feat(ec2): Ensure automatic acceptance of VPC attachment requests is disabled
prowler-cloud/prowler pull request #4765
Opened 2024-08-16 11:45 UTC by MarioRgzLpz

### Context

This check verifies whether EC2 transit gateways are automatically accepting shared VPC attachments. The check fails if a transit gateway is set to automatically accept shared VPC attachment requests. In order to make the check I have to modify `EC2` service to add a new model and a new method.

### Description

I added `ec2_transport_gateways_autoaccept_shared_attachments_enabled` check with his respective unit test. I added `TransportGateway` model and `describe_transport_gateways` to ec2 service with respective unit test.

### Checklist

- Are there new checks included in this PR? Yes 
    - If so, do we need to update permissions for the provider? No
- [X] Review if the code is being covered by tests.
- [X] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-21 12:51 UTC, sergargar commented on prowler/providers/aws/services/ec2/ec2_transport_gateways_autoaccept_shared_attachments_enabled/ec2_transport_gateways_autoaccept_shared_attachments_enabled.metadata.json
> +  "CheckID": "ec2_transport_gateways_autoaccept_shared_attachments_enabled",
```suggestion
  "CheckID": "ec2_transitgateway_auto_accept_vpc_attachments",
```

2024-08-21 12:51 UTC, sergargar commented on prowler/providers/aws/services/ec2/ec2_transport_gateways_autoaccept_shared_attachments_enabled/ec2_transport_gateways_autoaccept_shared_attachments_enabled.metadata.json
> +      "Text": "Do not include sensitive information in user data within the launch templates, try to use Secrets Manager instead.",
Please, change this.

2024-08-21 12:52 UTC, sergargar commented on prowler/providers/aws/services/ec2/ec2_service.py
> +        self.transit_gateways = []
Please, use a dictionary.

2024-08-21 12:53 UTC, sergargar commented on tests/providers/aws/services/ec2/ec2_transport_gateways_autoaccept_shared_attachments_enabled/ec2_transport_gateways_autoaccept_shared_attachments_enabled_test.py
> +            },
Could you create a test with a tgw that does not have options?

2024-08-21 12:53 UTC, MrCloudSec requested changes
Please, review my comments.

2024-08-22 09:26 UTC, MarioRgzLpz commented
@sergargar Change to dictionary in commit [fed372a](https://github.com/prowler-cloud/prowler/pull/4765/commits/fed372a4d8b49a28134f711294230ea1c4089648) and rename check, metadata and default tgw test added in commit [bcbbda0](https://github.com/prowler-cloud/prowler/pull/4765/commits/bcbbda0d3532498b6b5e80e2320338bc5ae7f28d)

2024-08-22 12:25 UTC, sergargar approved these changes
👏🏼 👏🏼 👏🏼

2024-08-22 12:26 UTC, merged