feat(ec2): Client VPN Endpoints Should Have Client Connection Logging Enabled
prowler-cloud/prowler pull request #4804
Opened 2024-08-20 12:20 UTC by MarioRgzLpz

### Context

Ensure Client VPN endpoints have client connection logging enabled. The control fails if logging is not enabled for the endpoint. Client connection logs are crucial for tracking user activity and ensuring visibility into VPN usage.

Enabling connection logging helps in monitoring, auditing, and troubleshooting VPN connections, contributing to overall security and compliance.

### Description

I added `ec2_client_vpn_endpoint_connection_logging_enabled` check with respective unit tests. In order to that I modified ec2_service.py to add a new model VpnEndpoint and added respective test to ec2_service_test.py.
### Checklist

- Are there new checks included in this PR? Yes 
    - If so, do we need to update permissions for the provider? No
- [X] Review if the code is being covered by tests.
- [X] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-21 13:23 UTC, sergargar commented on prowler/providers/aws/services/ec2/ec2_client_vpn_endpoint_connection_logging_enabled/ec2_client_vpn_endpoint_connection_logging_enabled.py
> +                report.status_extended = f"Vpn Endpoint {vpn_endpoint.id} in region {vpn_endpoint.region} has client connection logging enabled."
```suggestion
                report.status_extended = f"Client VPN endpoint {vpn_endpoint.id} in region {vpn_endpoint.region} has connection logging enabled."
```

2024-08-21 13:23 UTC, sergargar commented on prowler/providers/aws/services/ec2/ec2_client_vpn_endpoint_connection_logging_enabled/ec2_client_vpn_endpoint_connection_logging_enabled.py
> +                report.status_extended = f"Vpn Endpoint {vpn_endpoint.id} in region {vpn_endpoint.region} does not have client connection logging enabled."
```suggestion
                report.status_extended = f"Client VPN endpoint {vpn_endpoint.id} in region {vpn_endpoint.region} does not have connection logging enabled."
```

2024-08-21 13:33 UTC, sergargar requested changes
Please, review my comments.

2024-08-22 08:12 UTC, MarioRgzLpz commented
@sergargar Status extended changes done in commit [588971b](https://github.com/prowler-cloud/prowler/pull/4804/commits/588971ba774811d26b610d62a996ce81d313c6a3)

2024-08-22 12:03 UTC, sergargar commented on tests/providers/aws/services/ec2/ec2_service_test.py
> +    @mock_aws
Why this?

2024-08-22 12:07 UTC, sergargar submitted a review, later dismissed
👏🏼 👏🏼

2024-08-22 12:30 UTC, sergargar approved these changes, later dismissed

2024-08-22 13:33 UTC, sergargar approved these changes

2024-08-22 13:57 UTC, merged