Prwlr 4520 classic load balancer should span multiple availability zones
prowler-cloud/prowler pull request #4829
Opened 2024-08-22 09:56 UTC by puchy22

### Context

Checks that Classic Load Balancers are configured with registered instances from at least the specified number of Availability Zones (AZs). The control fails if the load balancer does not span the minimum number of AZs specified.

### Description

- [x]  Modify service to add AZs to ELB
- [x]  Test service changes
- [x]  Add configurable parameter for the check
- [x]  Add check logic
- [x]  Add unit testing for the check

### Checklist

- Are there new checks included in this PR? Yes
    - If so, do we need to update permissions for the provider? No.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-23 14:25 UTC, MrCloudSec commented on prowler/providers/aws/services/elb/elb_is_in_multiple_az/elb_is_in_multiple_az.py
> +# https://docs.aws.amazon.com/securityhub/latest/userguide/elb-controls.html#elb-10
Please, remove this.

2024-08-23 14:28 UTC, MrCloudSec commented on prowler/providers/aws/services/elb/elb_is_in_multiple_az/elb_is_in_multiple_az.py
> +            report.status_extended = f"Classic Load Balancer {load_balancer.name} is not in at least {ELB_MIN_AZS} availability zones. Is only in {', '.join(load_balancer.availability_zones)}."
```suggestion
            report.status_extended = f"Classic Load Balancer {load_balancer.name} is not in at least {ELB_MIN_AZS} availability zones, it is only in {', '.join(load_balancer.availability_zones)}."
```

2024-08-23 14:28 UTC, sergargar commented on prowler/providers/aws/services/elb/elb_is_in_multiple_az/elb_is_in_multiple_az.py
> +                report.status_extended = f"Classic Load Balancer {load_balancer.name} is in {len(load_balancer.availability_zones)} availability zones. Currently in {', '.join(load_balancer.availabil
```suggestion
                report.status_extended = f"Classic Load Balancer {load_balancer.name} is in {len(load_balancer.availability_zones)} availability zones: {', '.join(load_balancer.availability_zones)}."
```

2024-08-26 10:43 UTC, jfagoagas requested changes

2024-08-26 10:43 UTC, jfagoagas commented on prowler/providers/aws/services/elb/elb_service.py
> +    availability_zones: Set[str]
```suggestion
    availability_zones: set[str]
```

2024-08-26 10:43 UTC, jfagoagas commented on prowler/providers/aws/services/elb/elb_service.py
> +from typing import Optional, Set
```suggestion
from typing import Optional
```

2024-08-26 10:46 UTC, jfagoagas approved these changes

2024-08-26 11:27 UTC, merged