docs(is_item_matched): update docstrings for method
prowler-cloud/prowler pull request #4836
Opened 2024-08-22 12:44 UTC by pedrooot

### Description

Update docstrings for `is_item_matched`

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-22 12:48 UTC, jfagoagas requested changes

2024-08-22 12:48 UTC, jfagoagas commented on prowler/lib/mutelist/mutelist.py
> +            tag (bool): If True the search will have a different logic due to the tags being ORed or ANDed.
Please give this some care and explain the new logic perform while checking for muted tags. Thanks!

2024-08-22 12:59 UTC, pedrooot commented on prowler/lib/mutelist/mutelist.py
> +            tag (bool): If True the search will have a different logic due to the tags being ORed or ANDed.
Done!

2024-08-23 07:23 UTC, jfagoagas commented on prowler/lib/mutelist/mutelist.py
> +                - Check of OR logic -> True if any of the tags is present in the
```suggestion
                - Check of OR logic -> True if any of the tags is present in the finding.
```

2024-08-23 07:23 UTC, jfagoagas approved these changes

2024-08-23 08:15 UTC, merged