feat(cloudfront): Ensure Cloudfront distributions have origin failover configured
prowler-cloud/prowler pull request #4868
Opened 2024-08-26 18:39 UTC by HugoPBrito

### Context

This check ensures that Amazon CloudFront distributions have origin failover configured to enhance availability.
This PR uses code from [PR-4867](https://github.com/prowler-cloud/prowler/pull/4867)

### Description

The check verifies that `CloudFront` distributions use an origin group with multiple origins (2 at least). Origin failover helps maintain high availability by redirecting traffic to a secondary origin if the primary origin fails.

### Checklist

- Are there new checks included in this PR? Yes
    - If so, do we need to update permissions for the provider? I do not think so
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-28 20:35 UTC, puchy22 submitted a review, later dismissed

2024-08-28 20:35 UTC, puchy22 commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.metadata.json
> +  "ResourceType": "AwsCloudFrontDistribution",
```suggestion
  "ResourceType": "AWSCloudFrontDistribution",
```

2024-08-28 20:35 UTC, puchy22 commented on prowler/providers/aws/services/ecr/ecr_service.py
> +        self.__threading_call__(self.__list_tags_for_resource__)
I think this kind of changes shouldn't be here

2024-08-28 20:35 UTC, puchy22 commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.py
> +                report.status_extended = f"CloudFront Distribution {distribution.id} has an origin group with two or more origins."
```suggestion
                report.status_extended = f"CloudFront Distribution {distribution.id} has an origin group with {len(distribution.origins)} origins."
```

2024-08-28 20:35 UTC, puchy22 commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.py
> +                break
Why is this here? I think this could lead in only add one finding to report, check it with multiple CloudFront Distributions to verify please.

2024-09-02 11:31 UTC, HugoPBrito commented
After conducting a more extensive research, I discovered that while `CloudFront` distributions can have more than two origins, only two can be configured simultaneously. The new logic leverages this restriction to set a boolean, resulting in a more streamlined, simple, yet effective service structure and check logic.

2024-09-11 14:51 UTC, sergargar requested changes
Please, review my comments. Thanks!

2024-09-11 14:51 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.metadata.json
> +    "NIST 800-53 Controls"
Please use the types from https://docs.aws.amazon.com/securityhub/latest/userguide/asff-required-attributes.html#Types

2024-09-11 14:51 UTC, MrCloudSec commented on prowler/providers/aws/services/cloudfront/cloudfront_service.py
> +                            origin_failover = True if origin_groups else False
Can you use `Distribution.DistributionConfig.OriginGroups.Quantity`? And check if there is a Origin Group that has 2 or more items to set the origin_failover True or False.

2024-09-11 14:51 UTC, MrCloudSec commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.py
> +                report.status_extended = f"CloudFront Distribution {distribution.id} has an origin group with 2 origins configured."
```suggestion
                report.status_extended = f"CloudFront Distribution {distribution.id} has an origin group with at least 2 origins configured."
```

2024-09-11 14:51 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.py
> +            report.status_extended = f"CloudFront Distribution {distribution.id} does not have an origin group configured with 2 origins."
```suggestion
            report.status_extended = f"CloudFront Distribution {distribution.id} does not have an origin group configured with at least 2 origins."
```

2024-09-12 20:33 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_service.py
> +                            origin_failover = True if origin_groups else False
You are only checking here if there are 1 or more origins, right?

2024-09-18 15:52 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_distributions_multiple_origin_failover_configured/cloudfront_distributions_multiple_origin_failover_configured.metadata.json
> +    "Availability"
```suggestion
    "redundancy"
```

2024-09-18 15:53 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_service.py
> +                            if origin_groups:
```suggestion
```

2024-09-18 15:54 UTC, sergargar commented on prowler/providers/aws/services/cloudfront/cloudfront_service.py
> +                                    if members.get("Quantity", 0) >= 2:
```suggestion
                                    if origin_group.get("Members", {}).get("Quantity", 0) >= 2:
```

2024-09-18 17:26 UTC, sergargar approved these changes

2024-09-18 17:26 UTC, merged