Add mixed regions test case for s3_access_point_public_access_block
prowler-cloud/prowler pull request #4877
Opened 2024-08-27 23:37 UTC by LefterisXefteris

Add mixed regions test case for s3_access_point_public_access_block
Description
This pull request adds a new test case to test_s3_access_point_public_access_block.py that checks the behavior of the s3_access_point_public_access_block check across multiple AWS regions.
Changes

Added test_access_points_mixed_regions function to test S3 access points in US East 1, EU West 1, and AP Southeast 2 regions
The new test case verifies correct handling of different public access block configurations across regions

Motivation
This test enhances the coverage of the existing test suite by ensuring the check correctly handles:

Access points in multiple regions within a single execution
Varied public access block configurations across different regions
Correct region reporting in the check results

Testing

Ran the new test case locally using pytest
Verified that all existing tests still pass
Checked that the new test fails appropriately when the check's logic is intentionally broken

Additional Notes

This test case doesn't require any changes to the main check logic, only adds to the test coverage
Follows the existing pattern of mocking AWS services to avoid actual AWS API calls during testing

Checklist

 My code follows the style guidelines of this project
 [] I have performed a self-review of my own code
 [] I have commented my code, particularly in hard-to-understand areas
 [] I have made corresponding changes to the documentation (if applicable)
[] My changes generate no new warnings
 [] I have added tests that prove my fix is effective or that my feature works
 [] New and existing unit tests pass locally with my changes

2024-08-28 06:33 UTC, pedrooot requested changes, later dismissed
Thanks for taking care of this! 🔝 💯

2024-08-28 06:33 UTC, pedrooot commented on tests/providers/aws/services/s3/s3_access_point_public_access_block/s3_access_point_public_access_block_test.py
> +                assert result[2].region == "ap-southeast-2"
Could you add more assertions? (`status_extended`, `resource_id`,  `resource_arn`...) take a look at `test_access_points_without_public_access_block` and try to add all those asserts 🙏🏼

2024-08-28 07:12 UTC, pedrooot commented
Also, review https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/introduction/#contributing-with-your-code-or-fixes-to-prowler to fix the failing pr-tests 🙏🏼

2024-09-12 18:20 UTC, sergargar commented
Test has been improved with the needed asserts, thanks @LefterisXefteris !

2024-09-12 18:20 UTC, MrCloudSec approved these changes

2024-09-12 19:58 UTC, merged