feat: Slack integration for critical medium high low mute alerts #4843
prowler-cloud/prowler pull request #5042
Opened 2024-09-15 04:22 UTC by abant07

### Context

Currently, the slack report aggregates the checks that are found for a specific user by displaying the amount of passed checks, the amount of failed checks, and the number of resources that were checked. However, this is not very descriptive for the customer and it would be nice to have an additional section that lists the checks that are included in the findings (passed and failed)

If fixes an issue please add it with `Fix #4843 

### Description

I changed the slack.py file and the outputs.py file. In the outputs.py file I added an additional 2 key value pair in the stats hashmap (critical_failed_findings and critical_failed_findings). Since we cannot list all the checks that are included in a customer's account across all 3 providers, because some accounts will have thousands of checks. However, instead, I made it so that it lists the checks are marked as critical for both passed and failed findings. 

In the slack.py file I added two additional sections below the parameter args markdown, where it will iterate through all the finding check_names and display the critical passed and critical failed findings.
### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-16 12:56 UTC, sergargar commented
Hi @abant07, thanks for your contribution!

However, for large reports we may encounter the following error:
`[ERROR] must be less than 3001 characters`

This is due to multiple critical passed/failed findings that are making the Slack message too long, we can maybe put the number of critical findings, what do you think?

2024-09-16 12:56 UTC, sergargar requested changes

2024-09-16 12:56 UTC, sergargar commented on prowler/lib/outputs/outputs.py
> +        "total_muted_fail": 0,
```suggestion
```

2024-09-16 17:04 UTC, abant07 commented
Sure, I can put number of critical, high, medium, and low findings @sergargar  for pass and failed

2024-09-16 17:43 UTC, abant07 commented
Hey @sergargar . You are right. I think even if I did add all the counts for high, critical, informational, low, and medium, it would go over the 3000 character limit. So I have just follow you and put the counts for critical for both pass and fail

2024-09-16 22:17 UTC, abant07 commented
Hey @sergargar do you know why the accessanalyzer check is failing, I did not edit it.

2024-09-17 12:45 UTC, sergargar commented
> Hey @sergargar do you know why the accessanalyzer check is failing, I did not edit it.

no worries, it is some issue affecting all PRs.

2024-09-17 12:51 UTC, MrCloudSec commented
@abant07 I am getting the following error:
`ERROR: KeyError[159]: 'total_informational_severity_pass'`

Can you take it a look, please?

2024-09-17 17:56 UTC, abant07 commented
done. I realized there are no checks that have information severity. Unless I missed one. So for now, I put critical, high, medium, low

2024-09-19 15:02 UTC, sergargar commented
Thanks @abant07 ! Can you put the severities horizontally so the message has less height?

2024-09-19 15:09 UTC, abant07 commented
Sure no problem, I can do that

2024-09-19 18:01 UTC, sergargar approved these changes
Thanks for the contribution!

2024-09-19 18:02 UTC, merged