Fix: Incorrect filtering in LightSail service due to double call of i…
prowler-cloud/prowler pull request #5044
Opened 2024-09-15 12:12 UTC by h4r5h1t

- Corrected the conditional statement to call is_resource_filtered only once.
- Closes #5043

2024-09-16 08:42 UTC, jfagoagas requested changes, later dismissed

2024-09-16 08:42 UTC, jfagoagas commented on prowler/providers/aws/services/lightsail/lightsail_service.py
> +                    if not self.audit_resources or (
Could you please add some tests for this behaviour? We should verify that this behaviour is working as expected.

2024-09-20 15:37 UTC, sergargar commented
Approving this PR and we will add the missing tests when we add testing for `is_resource_filtered ` function in all checks.

2024-09-20 15:37 UTC, sergargar approved these changes

2024-09-20 15:39 UTC, merged