fix(aws): handle none type attributes
prowler-cloud/prowler pull request #5216
Opened 2024-09-26 18:44 UTC by sergargar

### Description

Handle `None` type attributes in checks:
- `organizations_scp_check_deny_regions`
- `ecr_repositories_not_publicly_accessible`

Also, fix typo in work `accessible`.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-27 07:39 UTC, jfagoagas requested changes

2024-09-27 07:39 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_scp_check_deny_regions/organizations_scp_check_deny_regions.py
Could you please add tests for the following lines:
- 74
- 82 to 85
- 88 to 90

If we are changing the logic of the check we should cover those scenarios.

2024-09-27 13:10 UTC, sergargar commented on prowler/providers/aws/services/organizations/organizations_scp_check_deny_regions/organizations_scp_check_deny_regions.py
@jfagoagas the logic of the check was not changed, only the following line was added:
`if org.policies is not None: # Access denied to list policies`

2024-09-30 10:00 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_scp_check_deny_regions/organizations_scp_check_deny_regions.py
Yes but even with that I think those lines are not being tested, you should add a test to verify when `org.policies is None`, don't you?

2024-09-30 14:01 UTC, sergargar commented on prowler/providers/aws/services/organizations/organizations_scp_check_deny_regions/organizations_scp_check_deny_regions.py
Yes, test was added!

2024-09-30 16:03 UTC, jfagoagas approved these changes
Great one, thanks @sergargar 🚀

2024-09-30 16:04 UTC, merged