feat(azure containerregistry): new check for restricted network access to an container registry
prowler-cloud/prowler pull request #5291
Opened 2024-10-04 08:34 UTC by johannes-engler-mw

### Context

Unrestricted network access to Azure Container registry should be restricted to enhance the security.

### Description

This PR adds an test for restricted network access to an Azure Container Registry.

### Checklist

- Are there new checks included in this PR? Yes
    - If so, do we need to update permissions for the provider? No
- [X] Review if the code is being covered by tests.
- [X] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-07 11:58 UTC, puchy22 requested changes

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted.metadata.json
> +  "Description": "Ensure that public network access to the Azure Container Registry is restricted to enhance security. This prevents unauthorized access and improves the overall security posture of t
```suggestion
  "Description": "Ensure that public network access to the Azure Container Registry is restricted.",
```

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted.py
> +            for registry_id, ContainerRegistryInfo in registries.items():
```suggestion
            for registry_id, container_registry_info in registries.items():
```

Please, use lower case and underscores for variables to follow our code style.

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_service.py
> +                                    registry, "network_rule_set", ""
```suggestion
                                    registry, "network_rule_set", None
```

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted.metadata.json
> +  "CheckID": "containerregistry_network_access_restricted",
```suggestion
  "CheckID": "containerregistry_not_publicly_accessible",
```

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted.py
> +class containerregistry_network_access_restricted(Check):
```suggestion
class containerregistry_not_publicly_accessible(Check):
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted_test.py
> +class TestContainerRegistryNetworkAcessRestricted:
Tenst
```suggestion
class Test_containerregistry_not_publicly_accessible:
```

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_service.py
> +from azure.mgmt.containerregistry import ContainerRegistryManagementClient, models
```suggestion
from azure.mgmt.containerregistry import ContainerRegistryManagementClient
from azure.mgmt.containerregistry import NetworkRuleSet
```

2024-10-07 11:58 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_service.py
> +    network_rule_set: models.NetworkRuleSet
```suggestion
    network_rule_set: NetworkRuleSet
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_admin_user_disabled/containerregistry_admin_user_disabled_test.py
> +                        network_rule_set="",
```suggestion
                        network_rule_set=None,
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_admin_user_disabled/containerregistry_admin_user_disabled_test.py
> +                        network_rule_set="",
```suggestion
                        network_rule_set=None,
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_service_test.py
> +                        network_rule_set="",
```suggestion
                        network_rule_set=None,
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted_test.py
> +from azure.mgmt.containerregistry import models
```suggestion
from azure.mgmt.containerregistry.models import NetworkRuleSet
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted_test.py
> +                        network_rule_set=models.NetworkRuleSet(default_action="Allow"),
```suggestion
                        network_rule_set=NetworkRuleSet(default_action="Allow"),
```

2024-10-07 11:58 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_network_access_restricted/containerregistry_network_access_restricted_test.py
> +                        network_rule_set=models.NetworkRuleSet(default_action="Deny"),
```suggestion
                        network_rule_set=NetworkRuleSet(default_action="Deny"),
```

2024-10-08 10:23 UTC, johannes-engler-mw commented
@puchy22 I have implemented your suggestions, please check again.

2024-10-09 09:05 UTC, puchy22 approved these changes, later dismissed
LGTM! 👍

2024-10-10 15:39 UTC, sergargar approved these changes

2024-10-10 15:39 UTC, merged