feat(autoscaling): add new check `autoscaling_group_multiple_instance_types`
prowler-cloud/prowler pull request #5325
Opened 2024-10-08 09:37 UTC by danibarranqueroo

### Context

This new check ensures that Amazon EC2 Auto Scaling groups use multiple instance types and deploy instances across multiple Availability Zones. Using multiple instance types enhances availability by allowing the Auto Scaling group to launch alternative instance types if there is insufficient capacity in the chosen Availability Zones, improving resilience and high availability.

I have done the check following [this](https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/AutoScaling/asg-multiple-instance-type-az.html) guide, but I have some concerns. While testing the check on real infrastructure, I realized that there are two ways to add instance types: either by adding a new instance attached to the Auto Scaling group or by adding a new override to the Launch Template to include new supported instance types.

Also, for the unit tests I needed to use botocore because moto does not cover the `attach_instance` api call.

### Description

Added new check `autoscaling_group_multiple_instance_types` with its unit tests.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-08 14:53 UTC, MrCloudSec requested changes

2024-10-08 14:53 UTC, MrCloudSec commented on prowler/providers/aws/services/autoscaling/autoscaling_group_multiple_instances_types_in_multiaz/autoscaling_group_multiple_instances_types_in_multiaz.metadata.json
> +  "CheckID": "autoscaling_group_multiple_instances_types_in_multiaz",
```suggestion
  "CheckID": "autoscaling_group_multiple_instance_types",
```

2024-10-08 14:53 UTC, MrCloudSec commented on prowler/providers/aws/services/autoscaling/autoscaling_group_multiple_instances_types_in_multiaz/autoscaling_group_multiple_instances_types_in_multiaz.py
Can we check if an AZ has more than one instance types?
For example, if there are 2 AZs and in one there are multiple instance types but in the other one only one instance type, it should fail.

2024-10-15 15:14 UTC, danibarranqueroo commented
Hi @sergargar!

These past few days, I’ve been working on other checks from this same service, and since they’re all merged now, I’ve finally made the changes you suggested. To do this, I needed to merge those checks into this branch and then start working on how to verify if each AZ has multiple instances. I decided to store each instance's AZ in a dictionary, using the AZ name as the key and the instance type as the value. During the check, I verify if each AZ has 2 or more values.

Since Moto still doesn’t support the `attach_instances` API call, I’ve kept the old `describe_autoscaling_groups` test, which covers the other Auto Scaling checks, and created a new test specifically for this Auto Scaling group with attached instances.

Hope this message helps you understand what I’ve done more quickly :rocket:😄

2024-10-15 18:47 UTC, sergargar approved these changes

2024-10-15 19:36 UTC, merged