feat(azure): add authentication method from static credentials
prowler-cloud/prowler pull request #5358
Opened 2024-10-10 11:15 UTC by pedrooot

### Description

This Pull Request (PR) adds a new method for instantiating the Azure provider exclusively using client_id, tenant_id and client_secret.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [X] Review if the code is being covered by tests.
- [X] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [X] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-11 07:26 UTC, jfagoagas requested changes

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +        azure_config = None
Could we name this `credentials` or `azure_credentials`?

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +            azure_config = self.get_statics_credentials(
Since you are not doing anything but creating a `dict` I think the function is not needed nor the `if`.

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +                raise AzureTenantIDNoBrowserAuthError(
I'd create a different error here since we are not using browser auth.

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +                    try:
Why another `try`?

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +        azure_config: dict,
I think it'd be simpler if you just add three new arguments here and the pass them using the `**dict` so you can unpack it into arguments. But this is up to you, nothing super important.

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +                    except Exception as error:
We need to catch the possible exceptions from the `ClientSecretCredential`, if any.

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/azure_provider.py
> +                    # DefaultAzureCredential sets the auth method excluding the others
```suggestion
                    # Since the authentication method to be used will come as True, we have to negate it since
                    # DefaultAzureCredential sets just one authentication method, excluding the others
```

2024-10-11 07:26 UTC, jfagoagas commented on prowler/providers/azure/exceptions/exceptions.py
> +class AzureConfigCredentialsError(AzureCredentialsError):
Can we create more? Like testing for:
- Invalid `client_id`
- Invalid `client_secret`
- Both valid but not belonging to `tenant_id`

2024-10-11 08:38 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +                raise AzureTenantIDNoBrowserAuthError(
Done

2024-10-11 08:38 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +            azure_config = self.get_statics_credentials(
Sure! Done

2024-10-11 09:13 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +                    try:
To handle the specific exceptions for the method from inside

2024-10-11 09:14 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +                    except Exception as error:
Done

2024-10-11 09:14 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +                    # DefaultAzureCredential sets the auth method excluding the others
Done

2024-10-11 10:20 UTC, pedrooot commented on prowler/providers/azure/exceptions/exceptions.py
> +class AzureConfigCredentialsError(AzureCredentialsError):
Done

2024-10-11 10:36 UTC, pedrooot commented on prowler/providers/azure/azure_provider.py
> +        azure_config = None
Done!

2024-10-15 07:36 UTC, jfagoagas approved these changes
🤯 Azure always requires a ton, great one 👏

2024-10-15 07:37 UTC, merged