chore(aws): Add AWSSessionTokenExpired
prowler-cloud/prowler pull request #5378
Opened 2024-10-11 09:50 UTC by jfagoagas

### Description

Add `AWSSessionTokenExpired` exception.

### Checklist

- Are there new checks included in this PR? **No**
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [x] Review if backport is needed. -> **No**

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-11 10:37 UTC, pedrooot approved these changes
🥷 Thanks!

2024-10-11 13:27 UTC, sergargar commented on prowler/providers/aws/aws_provider.py
> +            logger.error(str(session_token_expired))
Why not using our logging pattern?
```suggestion
            `logger.critical(f"{session_token_expired.__class__.__name__}[{session_token_expired.__traceback__.tb_lineno}]: {session_token_expired})"`
```

2024-10-11 13:27 UTC, sergargar requested changes
Please view my comment.

2024-10-17 13:37 UTC, sergargar commented on prowler/providers/aws/aws_provider.py
> +            logger.error(str(session_token_expired))
We will review all our logs in the future.

2024-10-17 13:37 UTC, sergargar approved these changes

2024-10-17 13:43 UTC, merged