feat(mq): add new check `mq_broker_logging_enabled`
prowler-cloud/prowler pull request #5483
Opened 2024-10-21 11:39 UTC by HugoPBrito

### Context

`Amazon MQ ActiveMQ brokers` can stream audit logs to Amazon `CloudWatch Logs` to provide better visibility into security events and broker activities. Streaming logs to `CloudWatch` allows for the creation of alarms and metrics to monitor for suspicious activity or operational issues, enhancing security and compliance.

### Description

This check ensures that an `Amazon MQ ActiveMQ broker` is streaming audit logs to Amazon `CloudWatch Logs`. The check will fail if the broker is not configured to stream these logs.

### Checklist

- Are there new checks included in this PR? Yes.
    - If so, do we need to update permissions for the provider? No.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [x] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-24 18:42 UTC, sergargar commented on tests/providers/aws/services/mq/mq_service_test.py
> -        assert mq.brokers[broker_arn].auto_minor_version_upgrade
Do not delete this line.

2024-10-24 18:43 UTC, sergargar commented on prowler/providers/aws/services/mq/mq_broker_logging_enabled/mq_broker_logging_enabled.py
Please, check if both Audit and General logs are enabled.

2024-10-24 18:43 UTC, sergargar requested changes
Please, review my comments.

2024-10-25 17:51 UTC, HugoPBrito commented on prowler/providers/aws/services/mq/mq_broker_logging_enabled/mq_broker_logging_enabled.py
Done!

2024-10-25 21:30 UTC, sergargar approved these changes

2024-10-25 21:33 UTC, merged