fix(aws): add new check `cloudwatch_log_group_no_critical_pii_in_logs`
prowler-cloud/prowler pull request #5494
Opened 2024-10-21 20:39 UTC by sergargar

### Context
This PR adds a new check, `cloudwatch_log_group_no_critical_pii_in_logs`, to detect critical Personally Identifiable Information (PII) in CloudWatch logs using Microsoft Presidio. The goal is to enhance security by ensuring no sensitive PII (e.g., SSNs, credit card numbers) is logged, reducing the risk of privacy violations and compliance issues.

### Description
- New Check: `cloudwatch_log_group_no_critical_pii_in_logs` detects critical PII such as Social Security Numbers (SSNs), credit card numbers, and email addresses.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-30 12:18 UTC, puchy22 requested changes

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.metadata.json
> +  "Tags": {},
```suggestion
```
For now this is not contemplated in the metadata as a field. If this is a new metadata change it should not be included in this PR.

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.metadata.json
> +    "Secure development"
```suggestion
```
This does not look like a valid CheckTypes.

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_secrets_in_logs/cloudwatch_log_group_no_secrets_in_logs.metadata.json
>  {
I do not understand why are you changing metadata in this other check. Please review if this changes are intended.

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +                            print(pii_detection_result)
```suggestion
```

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +        )
```suggestion
class SecretsDict(dict[int, Set[str]]):
    """Dictionary to track unique PII types on each line."""

    def add_secret(self, line_number: int, pii_type: str) -> None:
        """Add a PII type to a specific line number, ensuring no duplicates."""
        self.setdefault(line_number, set()).add(pii_type)

    def __str__(self) -> str:
        """Generate a formatted string representation of the dictionary."""
        return ", ".join(
            f"{', '.join(sorted(pii_types))} on line {line_number}"
            for line_number, pii_types in sorted(self.items())
        )
```
Considering that you does not want duplicates in PII types, I think a set is more suitable data structure.

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +                                    f"at {timestamp} - {log_stream_pii[timestamp].to_string()}"
```suggestion
                                    f"at {timestamp} - {str(log_stream_pii[timestamp])}"
```

2024-10-30 12:18 UTC, puchy22 commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +from json import dumps
```suggestion
from json import dumps
from typing import Set
```

2024-11-04 15:19 UTC, puchy22 approved these changes
Awesome job! 💯

2024-11-04 15:20 UTC, merged

2024-11-11 15:15 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +        analyzer = AnalyzerEngine()
I think this can be done after line 20 at least not to get anything if no logs.

2024-11-11 15:15 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_critical_pii_in_logs/cloudwatch_log_group_no_critical_pii_in_logs.py
> +class SecretsDict(dict[int, Set[str]]):
What is the purpose of this class?