fix(AZURE): containerregistry_not_publicly_accesible is working badly…
prowler-cloud/prowler pull request #5938
Opened 2024-11-27 19:54 UTC by StylusFrost

### Context
The check is indicating that it is FAIL when it is really Disabled.
fix #5937

### Description

fix #5937

### Checklist

- Are there new checks included in this PR? No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-28 09:34 UTC, puchy22 requested changes
Great catch! Please review my comments and we can merge it.

2024-11-28 09:34 UTC, puchy22 commented on prowler/providers/azure/services/containerregistry/containerregistry_service.py
> +                                    if registry.public_network_access == "Disabled"
```suggestion
                                    if getattr(registry, "public_network_access" "Enabled") == "Disabled"
```
Please add this, as according to [Microsoft documentation](https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2023_11_01_preview.models.registry?view=azure-python) `public_network_access` is not mandatory and could be None.

2024-11-28 09:34 UTC, puchy22 commented on tests/providers/azure/services/containerregistry/containerregistry_service_test.py
> +            assert registry_info.public_network_access is False
```suggestion
            assert not registry_info.public_network_access
```

2024-11-28 14:50 UTC, StylusFrost commented
requested changes made 🚀

2024-11-29 09:27 UTC, jfagoagas approved these changes
Thanks for taking care of Prowler fixing this issue ❤️

2024-11-29 09:28 UTC, puchy22 approved these changes
Great catch! 💯

2024-11-29 13:06 UTC, merged