feat: add CIS v1.0.0 GitHub compliance
prowler-cloud/prowler pull request #6116
Opened 2024-12-10 15:42 UTC by HugoPBrito

### Context

As we are adding a new provider we need to ad its compliance.

### Description

Added the `CIS benchmark v1.0.0` compliance to Prowler.

### Checklist

- Are there new checks included in this PR? No.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [x] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-10 16:06 UTC, HugoPBrito commented
Still pending to add `README.md` changes to reflect the final status of the GitHub provider release, like the number of checks, services, etc.

2025-05-13 13:53 UTC, andoniaf commented on docs/tutorials/github/authentication.md
> +???+ note Ensure the corresponding environment variables are set up before running Prowler for automatic detection if you don't plan to provide any credentials.
```suggestion
???+ note Ensure the corresponding environment variables are set up before running Prowler for automatic detection if you don't plan to specify the login method.
```

2025-05-14 07:52 UTC, andoniaf approved these changes, later dismissed

2025-05-14 08:06 UTC, HugoPBrito reviewed
Reviewing the revision of my pr 🤪

2025-05-14 08:06 UTC, HugoPBrito commented on docs/index.md
> +Prowler allows allows you to scan your GitHub account, including your repositories, organizations or applications.
Please fix this typo.

2025-05-14 08:06 UTC, HugoPBrito commented on docs/index.md
> +Prowler allows allows you to scan your GitHub account, including your repositories, organizations or applications.
```suggestion
Prowler allows you to scan your GitHub account, including your repositories, organizations or applications.
```

2025-05-14 08:10 UTC, MrCloudSec commented on prowler/lib/outputs/finding.py
> +                output_data["region"] = "global"
```suggestion
```

2025-05-14 08:22 UTC, MrCloudSec approved these changes

2025-05-14 08:23 UTC, MrCloudSec requested changes
Please, add this PR to the changelog.

2025-05-14 08:31 UTC, MrCloudSec submitted a review, later dismissed

2025-05-14 08:46 UTC, MrCloudSec approved these changes

2025-05-14 08:47 UTC, merged