feat(microsof365): Add documentation and compliance file
prowler-cloud/prowler pull request #6195
Opened 2024-12-13 16:33 UTC by MarioRgzLpz

### Context

Write all documentation needed for a correctly set up to allow prowler scan microsoft365 and add the compliance file with the CIS 4.0 Microsoft465 Benchmark controls. 

### Description

Changed documentation files and fill the compliance file with all the CIS controls using `generate_compliance_json_from_csv_for_cis40_microsoft365`.

### Checklist

- Are there new checks included in this PR? No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [x] Review if the code is being covered by tests.
- [x] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [x] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2025-02-05 18:09 UTC, danibarranqueroo commented on docs/getting-started/requirements.md
> +```
```suggestion
```console
export AZURE_CLIENT_ID="XXXXXXXXX"
export AZURE_CLIENT_SECRET="XXXXXXXXX"
export AZURE_TENANT_ID="XXXXXXXXX"
```
```

2025-02-05 18:10 UTC, danibarranqueroo commented on docs/tutorials/microsoft365/create-prowler-service-principal.md
> +8. Copy the value of the secret, it is going to be used as `APP_CLIENT_SECRET` environment variable.
```suggestion
8. Copy the value of the secret, it is going to be used as `AZURE_CLIENT_SECRET` environment variable.
```

2025-02-05 18:18 UTC, danibarranqueroo commented on docs/tutorials/microsoft365/authentication.md
> +
```suggestion
This allows Prowler to authenticate against microsoft365 using the following methods:

- Service principal authentication by environment variables (Enterprise Application)
- Current CLI credentials stored
- Interactive browser authentication

To launch the tool first you need to specify which method is used through the following flags:

```console
# To use service principal authentication
prowler microsoft365 --sp-env-auth

# To use cli authentication
prowler microsoft365 --az-cli-auth

# To use browser authentication
prowler microsoft365 --browser-auth --tenant-id "XXXXXXXX"
```

```

2025-02-06 09:12 UTC, puchy22 requested changes

2025-02-06 09:12 UTC, puchy22 commented on docs/index.md
> +### Microsoft365
```suggestion
#### Microsoft365
```

2025-02-06 09:12 UTC, puchy22 commented on docs/index.md
> +### Microsoft365
In the beginning of Overview, line 167 and 407 missing add M365

2025-02-06 09:12 UTC, puchy22 commented on docs/getting-started/requirements.md
> +    For Prowler App only the Service Principal authentication method is supported.
```suggestion
    For Prowler App only the Service Principal with an application authentication method is supported.
```

2025-02-06 09:12 UTC, puchy22 commented on docs/getting-started/requirements.md
> +To use `--browser-auth`  the user needs to authenticate against Azure using the default browser to start the scan, also `tenant-id` is required.
```suggestion
To use `--browser-auth`  the user needs to authenticate against Azure using the default browser to start the scan, also `--tenant-id` flag is required.
```

2025-02-06 09:12 UTC, puchy22 commented on docs/tutorials/microsoft365/create-prowler-service-principal.md
> +# How to create Prowler Service Principal
This page does not make so much sense to me for two reason:
1. It is literally a copy/paste of an old version for the same Azure tutorial
2. That tutorial is for Azure, not for Microsoft365. It makes more sense to me make this tutorial using the Microsoft Admin Center. The problem with this is that it would be practically the same so better option might be to use the Azure tutorial but indicating that it could be done from Azure Portal or Admin Center portal in the same way.

2025-02-10 16:11 UTC, MrCloudSec approved these changes

2025-02-10 16:12 UTC, puchy22 approved these changes
👍

2025-02-10 16:13 UTC, merged